version: 2.1

commands:
  install_deps:
    steps:
      - run:
          name: Install Deps
          command: |
            npm install --prefix src/

jobs:
  ci-build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - install_deps
  linting:
    docker:
      - image: circleci/node:lts
    steps:
    - checkout
    - run:
        name: Linting
        command: |
          npm run test-lint --prefix src/

workflows:
  build-and-package:
    jobs:
      - ci-build
      - linting:
          requires:
            - ci-build
