version: 2.1

commands:
  install_deps:
    steps:
      - run:
          name: Install Deps
          command: |
            cd src/
            npm install

jobs:
  ci-build:
    docker:
      - image: circleci/node:lts
    environment:
      JEST_JUNIT_OUTPUT_DIR: test-results
    steps:
      - checkout
      - install_deps
      - run:
          name: Linting
          command: |
            cd src
            npm run test-lint
      - run:
          name: Unit Tests
          command: |
            cd src
            npm run test-unit
      - run:
          name: Code Coverage
          command: |
            cd src
            bash <(curl -s https://codecov.io/bash)
      - store_test_results:
          path: test-results

  integratation-testing:
    docker:
      - image: circleci/node:lts
      - image: mongo:4.0
    environment:
      APP_PORT: 5000
      JEST_JUNIT_OUTPUT_DIR: testing-output
    steps:
      - checkout
      - install_deps
      - run:
          name: Run Integratation Testing
          command: |
            cd src
            npm run test-integration
      - store_test_results:
          path: testing-output

workflows:
  build-and-package:
    jobs:
      - ci-build
      - integratation-testing:
          requires:
            - ci-build